# Cybershuttle SDK -  Molecular Dynamics
> Define, run, monitor, and analyze molecular dynamics experiments in a HPC-agnostic way.

This notebook shows how users can setup and launch a **NAMD** experiment with replicas, monitor its execution, and run analyses both during and after execution.

## Installing Required Packages

First, install the `airavata-python-sdk-test` package from the pip repository.

In [ ]:
%pip install --upgrade airavata-python-sdk-test

## Importing the SDK

In [1]:
%cd dev-tools/deployment/jupyterhub/user-container/MD
import airavata_experiments as ae
from airavata_experiments import md

/Users/yasith/projects/artisan/airavata/dev-tools/deployment/jupyterhub/user-container/MD

using legacy validation callback

Authenticated via saved access token!

## Authenticating

To authenticate for remote execution, call the `ae.login()` method.
This method will prompt you to enter your credentials and authenticate your session.

In [2]:
ae.login()

Authenticated via saved access token!

Once authenticated, the `ae.list_runtimes()` function can be called to list HPC resources that the user has access to.

In [3]:
runtimes = ae.list_runtimes()
ae.display(runtimes)

,id,cluster,category,queue_name,node_count,cpu_count,walltime
0,remote,login.expanse.sdsc.edu,gpu,gpu-shared,1,10,30
1,remote,login.expanse.sdsc.edu,cpu,shared,1,10,30
2,remote,anvil.rcac.purdue.edu,cpu,shared,1,24,30

## Uploading Experiment Files

Drag and drop experiment files onto the workspace that this notebook is run on.

```bash
(sh) $: tree data
data
├── b4pull.pdb
├── b4pull.restart.coor
├── b4pull.restart.vel
├── b4pull.restart.xsc
├── par_all36_water.prm
├── par_all36m_prot.prm
├── pull.conf
├── structure.pdb
└── structure.psf

1 directory, 9 files

```

## Defining a NAMD Experiment

The `md.NAMD.initialize()` is used to define a NAMD experiment.
Here, provide the paths to the `.conf` file, the `.pdb` file, the `.psf` file, any optional files you want to run NAMD on.
You can preview the function definition through auto-completion.

```python
def initialize(
    name: str,
    config_file: str,
    pdb_file: str,
    psf_file: str,
    ffp_files: list[str],
    other_files: list[str] = [],
    parallelism: Literal['CPU', 'GPU'] = "CPU",
    num_replicas: int = 1
) -> Experiment[ExperimentApp]
```

To add replica runs, simply call the `exp.add_replica()` function.
You can call the `add_replica()` function as many times as you want replicas.
Any optional resource constraint can be provided here.

You can also call `ae.display()` to pretty-print the experiment.

In [4]:
exp = md.NAMD.initialize(
    name="yasith_namd_experiment",
    config_file="data/pull_cpu.conf",
    pdb_file="data/structure.pdb",
    psf_file="data/structure.psf",
    ffp_files=[
      "data/par_all36_water.prm",
      "data/par_all36m_prot.prm"
    ],
    other_files=[
      "data/b4pull.pdb",
      "data/b4pull.restart.coor",
      "data/b4pull.restart.vel",
      "data/b4pull.restart.xsc",
    ],
    parallelism="CPU",
    num_replicas=1,
)
exp.add_replica(*ae.list_runtimes(cluster="login.expanse.sdsc.edu", category="cpu"))
ae.display(exp)

Added replica. (1 tasks in total)

,name,application,num_tasks,config_file,pdb_file,psf_file,ffp_files,parallelism,other_files,num_replicas
0,yasith_namd_experiment,NAMD,1,data/pull_cpu.conf,data/structure.pdb,data/structure.psf,"data/par_all36_water.prm, data/par_all36m_prot...",CPU,"data/b4pull.pdb, data/b4pull.restart.coor, dat...",1

## Creating an Execution Plan

Call the `exp.plan()` function to transform the experiment definition + replicas into a stateful execution plan.

In [5]:
plan = exp.plan()
ae.display(plan)

,plan_id,name,app_id,inputs,runtime,ref,pid,agent_ref,workdir,sr_host
0,None,yasith_namd_experiment_DB23,NAMD,{'MD-Instructions-Input': {'value': 'data/pull...,"{'id': 'remote', 'args': {'cluster': 'login.ex...",None,None,None,None,None

## Saving the Plan

A created plan can be saved locally (in JSON) or remotely (in a user-local DB) for later reference.

In [6]:
plan.save()  # this will save the plan in DB
plan.save_json("plan.json")  # save the plan state locally

Plan saved: 8d7a6a06-e513-4c4e-8d9e-9da915e0690e

## Launching the Plan

A created plan can be launched using the `plan.launch()` function.
Changes to plan states will be automatically saved onto the remote.
However, plan state can also be tracked locally by invoking `plan.save_json()`.

In [7]:
plan.launch()
plan.save_json("plan.json")

Preparing execution plan...
Confirming execution plan...
Launching tasks...
[Task] Executing yasith_namd_experiment_DB23 on Remote(args={'cluster': 'login.expanse.sdsc.edu', 'category': 'cpu', 'queue_name': 'shared', 'node_count': 1, 'cpu_count': 10, 'walltime': 30})
[Remote] Creating Experiment: name=yasith_namd_experiment_DB23
[AV] Preprocessing args...
[AV] Validating args...
[AV] Setting up runtime params...
[AV] Setting up application interface...
[AV] Setting up experiment...
[AV] Setting up experiment directory...
[AV] exp_dir: /Default_Project/yasith_namd_experiment_DB23_2024_12_17_15_58_01
[AV] abs_path: /media/volume/cybershuttle-gateway-storage/pjaya001@odu.edu/Default_Project/yasith_namd_experiment_DB23_2024_12_17_15_58_01/
[AV] Setting up file inputs...
InputDataObjectType(name='agent_id', value=None, type=0, applicationArgument='-a', standardInput=False, userFriendlyDescription=None, metaData=None, inputOrder=14, isRequired=False, requiredToAddedToCommandLine=True, dataStaged=False, storageResourceId=None, isReadOnly=False, overrideFilename=None)
InputDataObjectType(name='Constraints-PDB', value=None, type=3, applicationArgument=None, standardInput=False, userFriendlyDescription='Constraints file in pdb', metaData=None, inputOrder=7, isRequired=False, requiredToAddedToCommandLine=False, dataStaged=False, storageResourceId=None, isReadOnly=False, overrideFilename=None)
InputDataObjectType(name='Continue_from_Previous_Run?', value=None, type=0, applicationArgument=None, standardInput=False, userFriendlyDescription=None, metaData='{"editor": {"ui-component-id": "checkbox-input-editor", "config": {"options": [{"value": "yes", "text": "Yes"}]}}}', inputOrder=1, isRequired=False, requiredToAddedToCommandLine=False, dataStaged=False, storageResourceId=None, isReadOnly=False, overrideFilename=None)
InputDataObjectType(name='Coordinates-PDB-File', value=None, type=3, applicationArgument=None, standardInput=False, userFriendlyDescription='PDB coordinates files needed but could be uploaded using optional upload below together with other needed files', metaData=None, inputOrder=4, isRequired=False, requiredToAddedToCommandLine=False, dataStaged=False, storageResourceId=None, isReadOnly=False, overrideFilename=None)
InputDataObjectType(name='Execution_Type', value='GPU', type=0, applicationArgument='-t', standardInput=False, userFriendlyDescription='CPU or GPU executable to be used. If you chose GPU please make sure GPU partitions are selected at the Resource selection below. Delta reservation is for A40 Gpus. Replica runs needs to use GPU partition.', metaData='{"editor": {"ui-component-id": "radio-button-input-editor", "config": {"options": [{"value": "CPU", "text": " CPU"}, {"value": "GPU", "text": "GPU"}]}}}', inputOrder=0, isRequired=True, requiredToAddedToCommandLine=True, dataStaged=False, storageResourceId=None, isReadOnly=False, overrideFilename=None)
InputDataObjectType(name='FF-Parameter-Files', value=None, type=4, applicationArgument=None, standardInput=False, userFriendlyDescription='Force field parameter and related files (e.g, *.prm and *.str files) needed but could be uploaded using optional upload below together with other needed files', metaData=None, inputOrder=6, isRequired=False, requiredToAddedToCommandLine=False, dataStaged=False, storageResourceId=None, isReadOnly=False, overrideFilename=None)
InputDataObjectType(name='GPU Resource Warning', value="Change the Queue from CPU to a GPU one (A100X4 or A100X8 or MI100X4) using 'Select a Queue' clicking on 'Settings for Queue' below", type=0, applicationArgument=None, standardInput=False, userFriendlyDescription='The GPU Execution_Type  selected above  requires GPU partition selection. Otherwise it may lead to failed run.', metaData='{"editor": {"dependencies": {"show": {"Execution_Type": {"comparison": "equals", "value": "GPU"}}, "showOptions": {"isRequired": false}}}}', inputOrder=12, isRequired=False, requiredToAddedToCommandLine=False, dataStaged=False, storageResourceId=None, isReadOnly=False, overrideFilename=None)
InputDataObjectType(name='MD-Instructions-Input', value=None, type=3, applicationArgument='-i', standardInput=False, userFriendlyDescription='NAMD conf file/QuickMD conf file', metaData=None, inputOrder=3, isRequired=True, requiredToAddedToCommandLine=True, dataStaged=False, storageResourceId=None, isReadOnly=False, overrideFilename=None)
InputDataObjectType(name='Number of Replicas', value='1', type=1, applicationArgument='-n', standardInput=False, userFriendlyDescription='Specify the number of replicas. Make sure the resources requested are commensurate, such as as many nodes as replicas.', metaData='{"editor": {"dependencies": {"show": {"Replicate?": {"comparison": "equals", "value": "yes"}}, "showOptions": {"isRequired": true}}}}', inputOrder=10, isRequired=True, requiredToAddedToCommandLine=True, dataStaged=False, storageResourceId=None, isReadOnly=False, overrideFilename=None)
InputDataObjectType(name='Optional_Inputs', value=None, type=4, applicationArgument=None, standardInput=False, userFriendlyDescription='Any other optional and all needed inputs to be uploaded, for a modified DCD out please upload your instructions for modification in a file named ModDCD.tcl.', metaData=None, inputOrder=8, isRequired=False, requiredToAddedToCommandLine=False, dataStaged=False, storageResourceId=None, isReadOnly=False, overrideFilename=None)
InputDataObjectType(name='Previous_JobID', value='""', type=0, applicationArgument='-r', standardInput=False, userFriendlyDescription='JobID from the previous run from which the restart/reuse data is to be extracted.', metaData='{"editor": {"dependencies": {"show": {"Continue_from_Previous_Run?": {"comparison": "equals", "value": "yes"}}, "showOptions": {"isRequired": true}}}}', inputOrder=2, isRequired=True, requiredToAddedToCommandLine=True, dataStaged=False, storageResourceId=None, isReadOnly=False, overrideFilename=None)
InputDataObjectType(name='Protein-Structure-File_PSF', value=None, type=3, applicationArgument=None, standardInput=False, userFriendlyDescription='Protein structure file (psf) needed but could be uploaded using optional upload below together with other needed files', metaData=None, inputOrder=5, isRequired=False, requiredToAddedToCommandLine=False, dataStaged=False, storageResourceId=None, isReadOnly=False, overrideFilename=None)
InputDataObjectType(name='Replicate?', value=None, type=0, applicationArgument=None, standardInput=False, userFriendlyDescription='Optionally Specify if Replicated runs needed. Make sure the resources requested are commensurate, such as as many nodes as replicas.', metaData='{"editor": {"ui-component-id": "checkbox-input-editor", "config": {"options": [{"value": "yes", "text": "Yes"}]}}}', inputOrder=9, isRequired=False, requiredToAddedToCommandLine=False, dataStaged=False, storageResourceId=None, isReadOnly=False, overrideFilename=None)
InputDataObjectType(name='Restart_Replicas_List', value=None, type=0, applicationArgument='-l', standardInput=False, userFriendlyDescription='Optionally specify a comma delimited list of replicas to restart (incomplete runs from a previous job), Make sure the resources requested are commensurate, such as as many nodes as replicas.', metaData='{"editor": {"dependencies": {"show": {"Continue_from_Previous_Run?": {"comparison": "equals", "value": "yes"}}, "showOptions": {"isRequired": false}}}}', inputOrder=11, isRequired=False, requiredToAddedToCommandLine=True, dataStaged=False, storageResourceId=None, isReadOnly=False, overrideFilename=None)
InputDataObjectType(name='server_url', value='api.gateway.cybershuttle.org', type=0, applicationArgument='-s', standardInput=False, userFriendlyDescription=None, metaData=None, inputOrder=13, isRequired=False, requiredToAddedToCommandLine=True, dataStaged=False, storageResourceId=None, isReadOnly=False, overrideFilename=None)
[InputDataObjectType(name='agent_id', value='818fa30a-d2ca-476f-9a1a-660473ae4f5c', type=0, applicationArgument='-a', standardInput=False, userFriendlyDescription=None, metaData=None, inputOrder=14, isRequired=False, requiredToAddedToCommandLine=True, dataStaged=False, storageResourceId=None, isReadOnly=False, overrideFilename=None), InputDataObjectType(name='Constraints-PDB', value=None, type=3, applicationArgument=None, standardInput=False, userFriendlyDescription='Constraints file in pdb', metaData=None, inputOrder=7, isRequired=False, requiredToAddedToCommandLine=False, dataStaged=False, storageResourceId=None, isReadOnly=False, overrideFilename=None), InputDataObjectType(name='Continue_from_Previous_Run?', value=None, type=0, applicationArgument=None, standardInput=False, userFriendlyDescription=None, metaData='{"editor": {"ui-component-id": "checkbox-input-editor", "config": {"options": [{"value": "yes", "text": "Yes"}]}}}', inputOrder=1, isRequired=False, requiredToAddedToCommandLine=False, dataStaged=False, storageResourceId=None, isReadOnly=False, overrideFilename=None), InputDataObjectType(name='Coordinates-PDB-File', value='airavata-dp://e0c9721e-ec9b-4870-9501-2a9fce9ae018', type=3, applicationArgument=None, standardInput=False, userFriendlyDescription='PDB coordinates files needed but could be uploaded using optional upload below together with other needed files', metaData=None, inputOrder=4, isRequired=False, requiredToAddedToCommandLine=False, dataStaged=False, storageResourceId=None, isReadOnly=False, overrideFilename=None), InputDataObjectType(name='Execution_Type', value='CPU', type=0, applicationArgument='-t', standardInput=False, userFriendlyDescription='CPU or GPU executable to be used. If you chose GPU please make sure GPU partitions are selected at the Resource selection below. Delta reservation is for A40 Gpus. Replica runs needs to use GPU partition.', metaData='{"editor": {"ui-component-id": "radio-button-input-editor", "config": {"options": [{"value": "CPU", "text": " CPU"}, {"value": "GPU", "text": "GPU"}]}}}', inputOrder=0, isRequired=True, requiredToAddedToCommandLine=True, dataStaged=False, storageResourceId=None, isReadOnly=False, overrideFilename=None), InputDataObjectType(name='FF-Parameter-Files', value='airavata-dp://e98bd65a-7b69-49ab-803f-6d068c4db67b,airavata-dp://d7ae0f68-5ded-4f26-9e4e-825d671b31d5', type=4, applicationArgument=None, standardInput=False, userFriendlyDescription='Force field parameter and related files (e.g, *.prm and *.str files) needed but could be uploaded using optional upload below together with other needed files', metaData=None, inputOrder=6, isRequired=False, requiredToAddedToCommandLine=False, dataStaged=False, storageResourceId=None, isReadOnly=False, overrideFilename=None), InputDataObjectType(name='GPU Resource Warning', value="Change the Queue from CPU to a GPU one (A100X4 or A100X8 or MI100X4) using 'Select a Queue' clicking on 'Settings for Queue' below", type=0, applicationArgument=None, standardInput=False, userFriendlyDescription='The GPU Execution_Type  selected above  requires GPU partition selection. Otherwise it may lead to failed run.', metaData='{"editor": {"dependencies": {"show": {"Execution_Type": {"comparison": "equals", "value": "GPU"}}, "showOptions": {"isRequired": false}}}}', inputOrder=12, isRequired=False, requiredToAddedToCommandLine=False, dataStaged=False, storageResourceId=None, isReadOnly=False, overrideFilename=None), InputDataObjectType(name='MD-Instructions-Input', value='airavata-dp://6524bc60-2b01-41ac-ad92-a8bf529f226f', type=3, applicationArgument='-i', standardInput=False, userFriendlyDescription='NAMD conf file/QuickMD conf file', metaData=None, inputOrder=3, isRequired=True, requiredToAddedToCommandLine=True, dataStaged=False, storageResourceId=None, isReadOnly=False, overrideFilename=None), InputDataObjectType(name='Number of Replicas', value='1', type=1, applicationArgument='-n', standardInput=False, userFriendlyDescription='Specify the number of replicas. Make sure the resources requested are commensurate, such as as many nodes as replicas.', metaData='{"editor": {"dependencies": {"show": {"Replicate?": {"comparison": "equals", "value": "yes"}}, "showOptions": {"isRequired": true}}}}', inputOrder=10, isRequired=True, requiredToAddedToCommandLine=True, dataStaged=False, storageResourceId=None, isReadOnly=False, overrideFilename=None), InputDataObjectType(name='Optional_Inputs', value='airavata-dp://6a87f266-b83d-4cbc-b46f-1a42237188f6,airavata-dp://c3c708da-f49a-4eb8-88c3-42db3d25c795,airavata-dp://a22b375e-d8e3-41fd-9b7d-02b00384b9ca,airavata-dp://f832b9b2-6c49-4ab1-a9a4-c32a25f8a8db', type=4, applicationArgument=None, standardInput=False, userFriendlyDescription='Any other optional and all needed inputs to be uploaded, for a modified DCD out please upload your instructions for modification in a file named ModDCD.tcl.', metaData=None, inputOrder=8, isRequired=False, requiredToAddedToCommandLine=False, dataStaged=False, storageResourceId=None, isReadOnly=False, overrideFilename=None), InputDataObjectType(name='Previous_JobID', value='""', type=0, applicationArgument='-r', standardInput=False, userFriendlyDescription='JobID from the previous run from which the restart/reuse data is to be extracted.', metaData='{"editor": {"dependencies": {"show": {"Continue_from_Previous_Run?": {"comparison": "equals", "value": "yes"}}, "showOptions": {"isRequired": true}}}}', inputOrder=2, isRequired=True, requiredToAddedToCommandLine=True, dataStaged=False, storageResourceId=None, isReadOnly=False, overrideFilename=None), InputDataObjectType(name='Protein-Structure-File_PSF', value='airavata-dp://eabd387a-05d7-45ae-a174-ccc7616eeaaa', type=3, applicationArgument=None, standardInput=False, userFriendlyDescription='Protein structure file (psf) needed but could be uploaded using optional upload below together with other needed files', metaData=None, inputOrder=5, isRequired=False, requiredToAddedToCommandLine=False, dataStaged=False, storageResourceId=None, isReadOnly=False, overrideFilename=None), InputDataObjectType(name='Replicate?', value=None, type=0, applicationArgument=None, standardInput=False, userFriendlyDescription='Optionally Specify if Replicated runs needed. Make sure the resources requested are commensurate, such as as many nodes as replicas.', metaData='{"editor": {"ui-component-id": "checkbox-input-editor", "config": {"options": [{"value": "yes", "text": "Yes"}]}}}', inputOrder=9, isRequired=False, requiredToAddedToCommandLine=False, dataStaged=False, storageResourceId=None, isReadOnly=False, overrideFilename=None), InputDataObjectType(name='Restart_Replicas_List', value=None, type=0, applicationArgument='-l', standardInput=False, userFriendlyDescription='Optionally specify a comma delimited list of replicas to restart (incomplete runs from a previous job), Make sure the resources requested are commensurate, such as as many nodes as replicas.', metaData='{"editor": {"dependencies": {"show": {"Continue_from_Previous_Run?": {"comparison": "equals", "value": "yes"}}, "showOptions": {"isRequired": false}}}}', inputOrder=11, isRequired=False, requiredToAddedToCommandLine=True, dataStaged=False, storageResourceId=None, isReadOnly=False, overrideFilename=None), InputDataObjectType(name='server_url', value='api.gateway.cybershuttle.org', type=0, applicationArgument='-s', standardInput=False, userFriendlyDescription=None, metaData=None, inputOrder=13, isRequired=False, requiredToAddedToCommandLine=True, dataStaged=False, storageResourceId=None, isReadOnly=False, overrideFilename=None)]
[OutputDataObjectType(name='Coordinate_Files', value='*_*.coor', type=4, applicationArgument=None, isRequired=False, requiredToAddedToCommandLine=False, dataMovement=False, location=None, searchQuery=None, outputStreaming=False, storageResourceId=None, metaData=None), OutputDataObjectType(name='NAMD-Standard-Error', value=None, type=6, applicationArgument=None, isRequired=True, requiredToAddedToCommandLine=False, dataMovement=False, location=None, searchQuery=None, outputStreaming=False, storageResourceId=None, metaData='{"file-metadata": {"mime-type": "text/plain"}}'), OutputDataObjectType(name='NAMD-Standard-Out', value=None, type=5, applicationArgument=None, isRequired=True, requiredToAddedToCommandLine=False, dataMovement=False, location=None, searchQuery=None, outputStreaming=False, storageResourceId=None, metaData='{"file-metadata": {"mime-type": "text/plain"}}'), OutputDataObjectType(name='Output_Index_files', value='*_*.idx', type=4, applicationArgument=None, isRequired=False, requiredToAddedToCommandLine=False, dataMovement=False, location=None, searchQuery=None, outputStreaming=False, storageResourceId=None, metaData=None), OutputDataObjectType(name='Output_PDB_Files', value='*_*.pdb', type=4, applicationArgument=None, isRequired=False, requiredToAddedToCommandLine=False, dataMovement=False, location=None, searchQuery=None, outputStreaming=False, storageResourceId=None, metaData=None), OutputDataObjectType(name='Output_PSF_Files', value='*_*.psf', type=4, applicationArgument=None, isRequired=False, requiredToAddedToCommandLine=False, dataMovement=False, location=None, searchQuery=None, outputStreaming=False, storageResourceId=None, metaData=None), OutputDataObjectType(name='Replica_Outputs', value='*_*.out', type=4, applicationArgument=None, isRequired=False, requiredToAddedToCommandLine=False, dataMovement=False, location=None, searchQuery=None, outputStreaming=False, storageResourceId=None, metaData=None), OutputDataObjectType(name='Restart_Files', value='*_*.restart.*', type=4, applicationArgument=None, isRequired=False, requiredToAddedToCommandLine=False, dataMovement=False, location=None, searchQuery=None, outputStreaming=False, storageResourceId=None, metaData=None), OutputDataObjectType(name='Trajectory-Files', value='*_*.dcd', type=4, applicationArgument=None, isRequired=False, requiredToAddedToCommandLine=False, dataMovement=False, location=None, searchQuery=None, outputStreaming=False, storageResourceId=None, metaData=None)]
[AV] Uploading 9 file inputs for experiment...

Output()

[AV] Experiment yasith_namd_experiment_DB23 CREATED with id: yasith_namd_experiment_DB23_ce9ce6db-cb14-431d-a30b-2dffcf0b72e7
[AV] Experiment yasith_namd_experiment_DB23 STARTED with id: yasith_namd_experiment_DB23_ce9ce6db-cb14-431d-a30b-2dffcf0b72e7
[AV] Experiment yasith_namd_experiment_DB23 WAITING until experiment begins...
[AV] Experiment yasith_namd_experiment_DB23 EXECUTING with pid: PROCESS_41e7a453-346d-444b-a406-d63af89ba064
[Remote] Experiment Launched: id=yasith_namd_experiment_DB23_ce9ce6db-cb14-431d-a30b-2dffcf0b72e7
Plan updated: 8d7a6a06-e513-4c4e-8d9e-9da915e0690e

## Checking the Plan Status
The status of a plan can be retrieved by calling `plan.status()`.

In [8]:
plan.status()

Plan 8d7a6a06-e513-4c4e-8d9e-9da915e0690e (1 tasks):
* yasith_namd_experiment_DB23: EXECUTING

## Loading a Saved Plan

A saved plan can be loaded by calling `ae.plan.load_json(plan_path)` (for local plans) or `ae.plan.load(plan_id)` (for remote plans).

In [9]:
plan = ae.plan.load_json("plan.json")
plan = ae.plan.load(plan.id)
plan.status()
ae.display(plan)

Plan 8d7a6a06-e513-4c4e-8d9e-9da915e0690e (1 tasks):
* yasith_namd_experiment_DB23: EXECUTING

,plan_id,name,app_id,inputs,runtime,ref,pid,agent_ref,workdir,sr_host
0,8d7a6a06-e513-4c4e-8d9e-9da915e0690e,yasith_namd_experiment_DB23,NAMD,{'MD-Instructions-Input': {'value': 'data/pull...,"{'id': 'remote', 'args': {'cluster': 'login.ex...",yasith_namd_experiment_DB23_ce9ce6db-cb14-431d...,PROCESS_41e7a453-346d-444b-a406-d63af89ba064,818fa30a-d2ca-476f-9a1a-660473ae4f5c,/Default_Project/yasith_namd_experiment_DB23_2...,iguide-cybershuttle.che070035.projects.jetstre...

## Fetching User-Defined Plans

The `ae.plan.query()` function retrieves all plans stored in the remote.

In [10]:
plans = ae.plan.query()
ae.display(plans)

,plan_id,name,app_id,inputs,runtime,ref,pid,agent_ref,workdir,sr_host
0,8d7a6a06-e513-4c4e-8d9e-9da915e0690e,yasith_namd_experiment_DB23,NAMD,{'MD-Instructions-Input': {'value': 'data/pull...,"{'id': 'remote', 'args': {'cluster': 'login.ex...",yasith_namd_experiment_DB23_ce9ce6db-cb14-431d...,PROCESS_41e7a453-346d-444b-a406-d63af89ba064,818fa30a-d2ca-476f-9a1a-660473ae4f5c,/Default_Project/yasith_namd_experiment_DB23_2...,iguide-cybershuttle.che070035.projects.jetstre...
1,acaabb04-3876-4c73-90d9-265f0984c09a,yasith_namd_experiment_BB6D,NAMD,{'MD-Instructions-Input': {'value': 'data/pull...,"{'id': 'remote', 'args': {'cluster': 'login.ex...",yasith_namd_experiment_BB6D_5365a12c-0b42-480f...,PROCESS_cff13fe6-5c11-4915-8be7-25da84edbaf7,ddbfe374-83e2-4151-bd02-cbd7fb676950,/Default_Project/yasith_namd_experiment_BB6D_2...,iguide-cybershuttle.che070035.projects.jetstre...

## Managing Plan Execution

The `plan.stop()` function will stop a currently executing plan.
The `plan.wait_for_completion()` function would block until the plan finishes executing.

In [11]:
# plan.stop()
plan.wait_for_completion()

Output()

Interrupted by user.

## Interacting with Files

The `task` object has several helper functions to perform file operations within its context.

* `task.ls()` - list all remote files (inputs, outputs, logs, etc.)
* `task.upload(<local_path>, <remote_path>)` - upload a local file to remote
* `task.cat(<remote_path>)` - displays contents of a remote file
* `task.download(<remote_path>, <local_path>)` - fetch a remote file to local

In [12]:
for task in plan.tasks:
    print(task.name, task.pid)
    # display files
    display(task.ls())
    # upload a file
    task.upload("data/sample.txt")
    # preview contents of a file
    display(task.cat("sample.txt"))
    # download a specific file
    task.download("sample.txt", f"./results_{task.name}")
    # download all files
    task.download_all(f"./results_{task.name}")

yasith_namd_experiment_DB23 PROCESS_41e7a453-346d-444b-a406-d63af89ba064

['pull_cpu.conf',
 'structure.pdb',
 'structure.psf',
 'par_all36_water.prm',
 'par_all36m_prot.prm',
 'b4pull.pdb',
 'b4pull.restart.coor',
 'b4pull.restart.vel',
 'b4pull.restart.xsc']

Output()

b'hello from the sample file!'

Output()

## Executing Task-Local Code Remotely

The `@task.context()` decorator can be applied on Python functions to run them remotely within the task context.
The functions executed this way has access to the task files, as well as the remote compute resources.

**NOTE**: Currently, remote code execution is only supported for ongoing tasks. In future updates, we will support both ongoing and completed tasks. Stay tuned!

In [ ]:
for index, task in enumerate(plan.tasks):
    @task.context(packages=["numpy", "pandas"])
    def analyze() -> None:
        import numpy as np
        with open("pull.conf", "r") as f:
            data = f.read()
        print("pull.conf has", len(data), "chars")
        print(np.arange(10))
    analyze()